Images for events (121)
mjmorale/Eventum pull request #132
Opened 2020-04-17 14:48 UTC by JonatanBonjour

2020-04-22 16:35 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/EventBuilder.java
> +        ObjectUtils.verifyNotNull(mTitle, mDescription, mDate, mLocation);
Y a pas imageId dedans

2020-04-22 16:35 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/createevent/CreateEventFragment.java
> +    private static final int CHOOSE_PHOTO = 200;
A mettre dans UIConstants

2020-04-22 16:35 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/createevent/CreateEventFragment.java
> +        });
Pas d'interface. Faire une interface similaire à la database. Et mettre en suite dans le viewmodel

2020-04-22 16:35 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/createevent/MyAppGlideModule.java
> +}
ça sert à quoi, doc

2020-04-22 16:35 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/event/DefaultEventFragment.java
> +
? Enlever.

2020-04-22 16:35 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/event/DefaultEventFragment.java
> +            if (URL == null) URL = defaultURL;
Enlever

2020-04-22 16:35 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/event/DefaultEventFragment.java
> +        String defaultURL = getResources().getString(R.string.defaultImageURL);
Enlever

2020-04-22 16:35 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/main/swipe/CardArrayAdapter.java
> +        if (URL == null) URL = defaultURL;
Enlever

2020-04-22 16:35 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/main/swipe/EventDetailFragment.java
> +        if (URL == null) URL = getResources().getString(R.string.defaultImageURL);
Enlever

2020-04-22 19:34 UTC, JonatanBonjour commented on app/src/main/java/ch/epfl/sdp/ui/event/DefaultEventFragment.java
> +
ok, mais on a un bouton non cliquable alors

2020-04-22 20:18 UTC, ksabaa15 commented on app/src/main/java/ch/epfl/sdp/ui/createevent/MyAppGlideModule.java
> +}
j’ai rien pigé de cette classe

2020-04-22 20:18 UTC, ksabaa15 approved these changes
Cool, mais un peu de javadoc

2020-04-22 22:06 UTC, mjmorale requested changes

2020-04-22 22:06 UTC, mjmorale commented on app/src/main/java/ch/epfl/sdp/ui/createevent/CreateEventFragment.java
> +        });
L'interface devrait comprendre la possibilité de faire des callback

2020-04-23 11:18 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/createevent/CreateEventFragment.java
> +        mFactory.setStorage(new FirestoreStorage(FirebaseStorage.getInstance()));
Utiliser le ServiceProvider. A voir des exemples dans MainActivity

2020-04-23 11:18 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/createevent/CreateEventViewModel.java
> +    static class CreateEventViewModelFactory extends ParameterizedViewModelFactory {
Remplacer par DatabaseViewModelFactory. La database va devenir la dernière valeur.

2020-04-23 14:04 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/storage/Storage.java
> +}
Javadoc

2020-04-23 14:04 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/createevent/CreateEventViewModel.java
> +    }
Qu'est-ce qu'il se passe si y a une erreur ?

2020-04-23 14:04 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/createevent/MyAppGlideModule.java
> +public class MyAppGlideModule extends AppGlideModule {
Renommer

2020-04-23 15:16 UTC, Dietech commented
Faut ajouter des tests pour ton interface

2020-04-23 15:20 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/platforms/firebase/storage/FirestoreStorage.java
> +                callback.onSuccess(mUrl);
Ajouter un callback pour la tache. Pas de while loop pls.

2020-04-23 15:20 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/platforms/firebase/storage/FirestoreStorage.java
> +        });
Remplacer les new ... par des lambdas

2020-04-23 15:20 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/storage/Storage.java
> +    void uploadImage(@NonNull Uri imageUri, @NonNull FirestoreStorage.UrlReadyCallback callback);
Javadoc

2020-04-23 15:20 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/storage/Storage.java
> + * Interface for the FirestoreStorage.
Pas suffisant

2020-04-23 17:19 UTC, mjmorale approved these changes

2020-04-23 17:55 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/platforms/firebase/storage/FirestoreStorage.java
> +                    mUrl = urlTask.getResult().toString();
Utiliser task la dedans et vérifier si la tâche est successful sinon appeller le callback onFailure

2020-04-23 18:37 UTC, merged