200/201 map info view
mjmorale/Eventum pull request #205
Opened 2020-05-09 09:21 UTC by JonatanBonjour

2020-05-13 17:39 UTC, ksabaa15 requested changes
Nice work on the event hash idea, but the back button still doesn't work and it seems that Glide still glitches often. Sometimes it's the default image that pops out and sometimes it's the one of another event. The glide issue should be discussed with the assistants, but the back button should be easily fixed.

2020-05-13 17:39 UTC, ksabaa15 commented on app/src/main/java/ch/epfl/sdp/ui/main/swipe/SwipeFragment.java
> +            eventHash = bundle.getInt("eventHash", DEFAULT_VALUE);
as long as it works

2020-05-13 19:16 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/main/swipe/SwipeFragment.java
> +            eventHash = bundle.getInt("eventHash", DEFAULT_VALUE);
A mettre dans UIConstants

2020-05-13 19:16 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/main/swipe/SwipeFragment.java
> +        if (mArrayAdapter.isEmpty() && bundleEventHash() != DEFAULT_VALUE) {
Pourquoi pas utiliser mEventHash à la place de bundleEventHash ?

2020-05-13 19:16 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/main/swipe/SwipeFragment.java
> +            getActivity().getSupportFragmentManager().beginTransaction().replace(R.id.main_container, new MapFragment()).commit();
Pas moyen de faire passer cette ligne dans les tests ?

2020-05-13 19:57 UTC, JonatanBonjour commented
> Nice work on the event hash idea, but the back button still doesn't work and it seems that Glide still glitches often. Sometimes it's the default image that pops out and sometimes it's the one of another event. The glide issue should be discussed with the assistants, but the back button should be easily fixed.

For the back button, Corentin still need to work on it.

2020-05-13 21:25 UTC, JonatanBonjour commented on app/src/main/java/ch/epfl/sdp/ui/main/swipe/SwipeFragment.java
> +            eventHash = bundle.getInt("eventHash", DEFAULT_VALUE);
je trouve que c'est pas vraiment lié à l'UI, non ?

2020-05-14 09:30 UTC, JonatanBonjour commented
> > Nice work on the event hash idea, but the back button still doesn't work and it seems that Glide still glitches often. Sometimes it's the default image that pops out and sometimes it's the one of another event. The glide issue should be discussed with the assistants, but the back button should be easily fixed.
> 
> For the back button, Corentin still need to work on it.
I have managed to fix it, it's working now.

2020-05-14 10:16 UTC, MartinBeaussart approved these changes

2020-05-14 10:39 UTC, ksabaa15 approved these changes

2020-05-14 10:58 UTC, merged