144 user profile
mjmorale/Eventum pull request #217
Opened 2020-05-11 15:36 UTC by MartinBeaussart

2020-05-14 07:50 UTC, JonatanBonjour reviewed
Bon travail, n'oubliez pas d'ajouter la Javadoc !

2020-05-14 07:50 UTC, JonatanBonjour commented on app/build.gradle
> +    implementation "androidx.constraintlayout:constraintlayout:2.0.0-beta5"
beta nécessaire ? sinon prendre la dernière version stable

2020-05-14 07:50 UTC, JonatanBonjour commented on app/src/androidTest/java/ch/epfl/sdp/ui/user/UserProfileFragmentTest.java
> +    @Mock
retour à la ligne entre les mocks

2020-05-14 07:50 UTC, JonatanBonjour commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileViewModel.java
> +public class UserProfileViewModel extends ViewModel {
c'est mieux de mettre la factory au début, comme sur notre template de view model

2020-05-14 11:27 UTC, dmizr requested changes

2020-05-14 11:27 UTC, dmizr commented on app/src/main/res/layout/fragment_user_profile.xml
> +    </androidx.cardview.widget.CardView>
Vraiment pas fan de tout ce layout.

C'est mieux de définir les constraints vis à vis des autres éléments (par exemple, définir la position de la boite de texte relative à celle du user profile, au lieu de relatif au bord de l'écran), car sinon l'affichage peut devenir problématique selon la taille et le format de l'écran. Plus d'infos: https://developer.android.com/training/constraint-layout

2020-05-14 11:27 UTC, dmizr commented on app/src/main/res/values/colors.xml
> +    <color name="white_grey">#EDEDED</color>
il faut garder les noms consistants (`white_grey` est en snakecase, `headerTextColor` est en camelCase)

2020-05-14 11:27 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileViewModel.java
> +    }
il faut ajouter la javadoc

2020-05-14 11:27 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileViewModel.java
> +        }
- renommer la factory pour avoir un nom plus descriptif (par exemple, `UserProfileViewModelFactory`)
- mettre la factory au début
- ajouter la javadoc

2020-05-14 11:27 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileFragment.java
> +    }
javadoc

2020-05-14 11:27 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileFragment.java
> +        }
javadoc

2020-05-14 11:27 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileFragment.java
> +    }
javadoc

2020-05-14 11:27 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileFragment.java
> +    public UserProfileFragment(){
javadoc

2020-05-14 11:27 UTC, dmizr commented on app/src/main/res/drawable/bacround_gradient.xml
> +</shape>
mauvais nom de fichier, background est mal nommé (le renommer à `background` au lieu de `bacround`)

2020-05-14 11:27 UTC, dmizr commented on app/src/main/res/layout/fragment_user_profile.xml
> +    </androidx.cardview.widget.CardView>
De plus, le layout réagit mal au inputs du clavier (certaines fois, seulement une partie des éléments bougent lorsque le clavier s'affiche, sii les éléments sont positionnés relatifs à d'autres, ce problème peut être évité.)

2020-05-14 11:27 UTC, dmizr commented on app/src/main/res/layout/fragment_user_profile.xml
> +    </androidx.cardview.widget.CardView>
Il n'y a aussi pas moyen de valider le texte et quitter la boite de description une fois que l'utilisateur décide d'éditer sa description. Le clavier reste toujours affiché car il n'y a pas de bouton "send" ou "validate" sur le clavier, seulement un retour à la ligne. 

Ça serait pas mal de s'inspirer de `fragment_chat.xml` pour une partie du layout (comme la description).

2020-05-14 12:03 UTC, ros-dorian commented on app/src/main/java/ch/epfl/sdp/User.java
>      }
Enlever.

2020-05-14 12:03 UTC, ros-dorian commented on app/src/main/java/ch/epfl/sdp/User.java
> +        this.mDescription=verifyNotNull(description);
vérifier qu'il sont pas empty

2020-05-14 12:03 UTC, ros-dorian commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileFragment.java
> +    public UserProfileFragment(Storage storage, Authenticator authenticator, Database database){
@NonNull

2020-05-14 12:03 UTC, ros-dorian commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileFragment.java
> +                    Toast.makeText(getContext(), "Operation failed, try again!", Toast.LENGTH_SHORT).show();
Message est pas précis. Qu'est-ce qui s'est mal passé?

2020-05-14 12:03 UTC, ros-dorian commented on app/src/main/java/ch/epfl/sdp/User.java
> +    }
Enlever

2020-05-14 12:03 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileFragment.java
> +        mViewModel.updateDescription(mBinding.userProfileBio.getText().toString());
Pourquoi pas update directement quand le texte change ?

2020-05-14 12:03 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileViewModel.java
> +        mUserCollection.document(mUserInfo.getUid()).update("description", description, new Query.OnQueryCompleteCallback<Void>() {
Mettre une lambda à la place d'une classe anonyme et handle le résultat.

2020-05-14 12:03 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileViewModel.java
> +    }
ditto

2020-05-14 12:03 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileFragment.java
> +                mViewModel.getStorage().uploadImage(mImageUri, mUploadCallBack);
Créer une fonction à l'intérieur du viewmodel

2020-05-14 12:17 UTC, ksabaa15 commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileFragment.java
> +                    Toast.makeText(getContext(), "Operation failed, try again!", Toast.LENGTH_SHORT).show();
J'ai pas un source d'info que je peux imprimer, je sais pas c'est quoi le probleme.

2020-05-14 12:20 UTC, ksabaa15 commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileFragment.java
> +        mViewModel.updateDescription(mBinding.userProfileBio.getText().toString());
l'utilisateur n'as aucune idee, il voit les changement devant lui sur le text input, et des qu'il quite la vue ca va update dans la database. ca evite de update plusieur fois.

2020-05-14 13:47 UTC, JonatanBonjour approved these changes

2020-05-14 17:31 UTC, dmizr requested changes

2020-05-14 17:31 UTC, dmizr commented on app/src/main/res/layout/fragment_user_profile.xml
> +                android:hint="Write about youself here"
Typo: `youself` au lieu de `yourself`

2020-05-14 17:31 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileFragment.java
> +    public void loadImage(FirestoreStorage.UrlReadyCallback uploadCallBack) {
l'app crash si l'image est de haute résolution (par exemple si elle vient d'une photo du téléphone), je pense qu'il faut resize l'image à une résolution plus basse avant de la stocker dans firebase

2020-05-14 17:56 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileFragment.java
> +                    Toast.makeText(getContext(), "Operation failed, try again!", Toast.LENGTH_SHORT).show();
Non mais tu sais que tu étais en train d'essayer de mettre à jour ta photo de profil donc peut être que "Cannot change the profile picture, try again later" est plus approprié

2020-05-14 17:56 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileFragment.java
> +        mViewModel.updateDescription(mBinding.userProfileBio.getText().toString());
Je pense que utiliser le lifecycle de l'activiter pour gérer ça est une mauvaise idée

2020-05-20 17:25 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/ChatFragment.java
> +        mAdapter.setContext(getContext());
C'est pas dupliqué ça ? Tu passes le context au constructeur mais tu fais setContext 5 lignes après ?

2020-05-20 17:25 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/MessageListAdapter.java
> +    }
Enlever ?

2020-05-20 17:25 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/MessageListAdapter.java
> +                });
Pas besoin de observe, get l'id une fois et affiche ça, ça évite de se retrouver avec pleins de listener inutiles.

2020-05-20 17:25 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/MessageListAdapter.java
> +        mContext=context;
VerifyNotNull

2020-05-20 17:25 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/MessageListAdapter.java
> +            if(mContext!=null)
Pas besoin en principe

2020-05-20 17:25 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/main/MainActivity.java
> +                    ImageGetter.getInstance().getImage(getApplicationContext(), user.getImageId(),mMainNavHeaderView.findViewById(R.id.main_nav_header_profile_picture));
getContext à la place de getApplicationContext

2020-05-20 17:25 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileFragment.java
> +    }
Enlever

2020-05-20 17:25 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileFragment.java
> +                mViewModel.setImage(data.getData(), getContext(), mBinding.userProfilePhoto, mUploadCallBack);
Pourquoi pas mettre le upload callback la dedans au lieu de devoir le sauver dans le fragment ?

2020-05-20 17:25 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileFragment.java
> +                    mViewModel.updateImageId(url);
ça devrait être dans le viewmodel ça -> pas besoin de updateImageId

2020-05-20 17:25 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileViewModel.java
> +        mUserInfo = authenticator.getCurrentUser();
verifyNotNull

2020-05-20 17:25 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileViewModel.java
> +        });
Pas de gestion d'erreur

2020-05-20 17:25 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileViewModel.java
> +    }
Peut être mis dans setImage

2020-05-20 17:25 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileViewModel.java
> +        imageView.setTag("new_image");
Pas besoin puisque tu as le listener dans le fragment

2020-05-20 17:25 UTC, Dietech commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileViewModel.java
> +    }
Enlever

2020-05-20 17:40 UTC, ksabaa15 commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileViewModel.java
> +        imageView.setTag("new_image");
c'est pour les tests

2020-05-20 17:40 UTC, ksabaa15 commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileViewModel.java
> +        imageView.setTag("new_image");
c'est pour les tests

2020-05-20 17:49 UTC, ksabaa15 commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/MessageListAdapter.java
> +                });
je ne sais pas comment faire ca asyncro d'une autre facon qu'avec des observeur. si je fais livedata.getValue().getId() ca va fail bien evidement.

2020-05-20 21:17 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/MessageListAdapter.java
> +    private static Context mContext;
Pourquoi les avoir ici et ne pas les mettre dans le viewmodel?

2020-05-20 21:44 UTC, dmizr requested changes

2020-05-20 21:44 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/MessageListAdapter.java
> +                });
pourquoi pas faire cette query en utilisant le viewmodel ou la faire directement dans le fragment?
Par exemple, lorsque tu récupères la liste de ChatMessage, tu peux associer à chaque ChatMessage un User et donner la liste de paires (ChatMessage, User) comme argument pour l'adapter

2020-05-20 21:44 UTC, dmizr commented on app/src/main/res/layout/fragment_user_profile.xml
> +                android:layout_centerHorizontal="true"
apparement ça n'existe pas layout_centerHorizontal (d'après cirrus)

2020-05-20 21:44 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/MessageListAdapter.java
> +        mContext=context;
Donner le contexte et la database directement dans l'adapter me semble être incorrect, je pense que ça devrait être fait dans le fragment ou viewmodel (pour la database), à vérifier

2020-05-20 21:44 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/ChatViewModel.java
> +import android.provider.ContactsContract;
il sert à quoi cet import?

2020-05-20 21:44 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/MessageListAdapter.java
> +                });
En testant le chat, j'ai eu un freeze de quelques secondes en loadant le chat car la photo de profil de Michel n'avait pas load. Je pense que c'est lié au problème des images trop haute résolution et du fetching d'images pas asynchrone, et je pense que ça va être fixé dans une autre branche, mais il faut vérifier que ce problème n'ait pas aussi lieu avec des images basses résolution, et s'assurer que toutes les images stockées sont d'une assez basse résolution

2020-05-21 00:41 UTC, ksabaa15 commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/MessageListAdapter.java
> +                });
Si tu voulais dire, faire ceci avec un simple observeur, j'ai un lifecycleOwner dans le viewmodel

2020-05-21 00:43 UTC, ksabaa15 commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileViewModel.java
> +    }
Set image c'est pour la display, updateImageID c'est pour la update dans la base des donnes

2020-05-21 00:52 UTC, ksabaa15 commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/MessageListAdapter.java
> +        mContext=context;
Pas seulement ca casserai l'abstraction de remplir les images des messages dans le fragment, ca va etre vraiment impratique ce choix d'implementation.

2020-05-21 09:50 UTC, dmizr requested changes

2020-05-21 09:50 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/ChatFragment.java
> +                LiveData<User> userLive = database.query("users").document(messageObject.getObject().getUid()).liveData(User.class);
cette query devrait être faite dans le ViewModel (qui a accès à la database et peut donc faire la query)

2020-05-21 09:50 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/ChatViewModel.java
> +    }
mettre au début après la factory

2020-05-21 09:50 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/ChatViewModel.java
> +
mettre au début (comme c'était fait avant)

2020-05-21 09:50 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/MessageListAdapter.java
> +            nameText.setText(message.getName());
mettre le nom fourni par User (maintenant qu'on a un user associé à chaque user) au lieu de mettre le nom donné dans le message (je crois que c'est avec user.getName())

2020-05-21 09:50 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/MessageListAdapter.java
> +                });
c'est nécessaire de mettre observeForever au lieu de juste observe?

2020-05-21 09:50 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/user/profile/UserProfileViewModel.java
> +
mettre la factory au début au lieu de la mettre à la fin

2020-05-21 10:10 UTC, ksabaa15 commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/MessageListAdapter.java
> +                });
pas de lifecycle owner ici

2020-05-21 10:15 UTC, ksabaa15 commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/MessageListAdapter.java
> +            nameText.setText(message.getName());
le message a été initialisé avec le nom du user, et le nom d'un user est non modifiable.

2020-05-21 10:56 UTC, dmizr requested changes

2020-05-21 10:56 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/ChatFragment.java
> +            Database database = ServiceProvider.getInstance().getDatabase();
plus besoin de cette ligne et d'accéder à la database je crois

2020-05-21 10:56 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/ChatViewModel.java
> +    }
plus besoin de getDatabase si les changements ont bien été faits

2020-05-21 10:56 UTC, dmizr commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/MessageListAdapter.java
> +                });
je sais pas si c'est possible mais je pense qu'il faut remove les observers lorsqu'ils sont plus nécessaire après un appel à observeForever (à vérifier avec quelqu'un d'autre plus familier avec les observers)

2020-05-21 11:12 UTC, ksabaa15 commented on app/src/main/java/ch/epfl/sdp/ui/event/chat/MessageListAdapter.java
> +                });
a revoir oui, sinon ca fait du sens si la photo de profie de qqun change pendant que tu est en train de ragarder le chat, pour pas avoir besoin de quiter le chat et revenir pour voir sa nouvelle photo de profile

2020-05-21 11:39 UTC, dmizr approved these changes

2020-05-21 11:39 UTC, merged